# Generated by Django 3.1.1 on 2020-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default='short', max_length=450),
            preserve_default=False,
        ),
    ]
