# Generated by Django 3.1.1 on 2020-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200903_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='baner/')),
                ('url', models.CharField(blank=True, max_length=350, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
